# ----------- BUILD STAGE -----------
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY .. .
WORKDIR /src/SnapTalesAPI

RUN dotnet restore
RUN dotnet publish -c Release -o /app

# ----------- RUNTIME STAGE -----------
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app .

ENV ASPNETCORE_URLS=http://+:10000
EXPOSE 10000

ENTRYPOINT ["dotnet", "SnapTalesAPI.dll"]
