using FluentMigrator;

namespace SnapTalesAPI.Data.Migrations
{
    /// <summary>
    /// Replaces the old SVG placeholder images on seeded products with proper PNG thumbnails.
    /// Thumbnails are generated by SampleOverlayService on first API startup.
    /// </summary>
    [Migration(202604290002)]
    public class ReplaceProductImages : Migration
    {
        // Same product GUIDs as SeedProductImages (202604280001)
        private const string Prod1 = "c3d4e5f6-0003-0000-0000-000000000001";  // Classic
        private const string Prod2 = "c3d4e5f6-0003-0000-0000-000000000002";  // Modern
        private const string Prod3 = "c3d4e5f6-0003-0000-0000-000000000003";  // Ornate
        private const string Prod4 = "c3d4e5f6-0003-0000-0000-000000000004";  // Rustic
        private const string Prod5 = "c3d4e5f6-0003-0000-0000-000000000005";  // Minimal
        private const string Prod6 = "c3d4e5f6-0003-0000-0000-000000000006";  // Gallery

        public override void Up()
        {
            // Replace SVG paths with proper PNG thumbnail paths.
            // Thumbnails are created by SampleOverlayService in images/products/thumbnails/.
            Execute.Sql($@"UPDATE public.""Products"" SET ""Images"" = '[""images/products/thumbnails/sample-classic-thumb.png""]' WHERE ""Id"" = '{Prod1}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""Images"" = '[""images/products/thumbnails/sample-modern-thumb.png""]'  WHERE ""Id"" = '{Prod2}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""Images"" = '[""images/products/thumbnails/sample-ornate-thumb.png""]'  WHERE ""Id"" = '{Prod3}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""Images"" = '[""images/products/thumbnails/sample-rustic-thumb.png""]'  WHERE ""Id"" = '{Prod4}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""Images"" = '[""images/products/thumbnails/sample-minimal-thumb.png""]' WHERE ""Id"" = '{Prod5}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""Images"" = '[""images/products/thumbnails/sample-gallery-thumb.png""]' WHERE ""Id"" = '{Prod6}'");

            // Also clear any remaining SVG paths from all other products (safety net)
            Execute.Sql(@"
                UPDATE public.""Products""
                SET ""Images"" = '[]'::jsonb
                WHERE ""Images""::text LIKE '%.svg%'
            ");
        }

        public override void Down()
        {
            // Restore SVG paths (for rollback purposes only — SVG files are deleted from disk)
            Execute.Sql($@"UPDATE public.""Products"" SET ""Images"" = '[""images/products/frame-classic.svg""]' WHERE ""Id"" = '{Prod1}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""Images"" = '[""images/products/frame-modern.svg""]'  WHERE ""Id"" = '{Prod2}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""Images"" = '[""images/products/frame-ornate.svg""]'  WHERE ""Id"" = '{Prod3}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""Images"" = '[""images/products/frame-rustic.svg""]'  WHERE ""Id"" = '{Prod4}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""Images"" = '[""images/products/frame-minimal.svg""]' WHERE ""Id"" = '{Prod5}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""Images"" = '[""images/products/frame-gallery.svg""]' WHERE ""Id"" = '{Prod6}'");
        }
    }
}
