using FluentMigrator;

namespace SnapTalesAPI.Data.Migrations
{
    [Migration(202604290001)]
    public class AddProductOverlayAndAperture : Migration
    {
        // Category GUIDs (must match CreateCategoriesSizesProducts)
        private const string CatClassic = "a1b2c3d4-0001-0000-0000-000000000001";
        private const string CatModern  = "a1b2c3d4-0001-0000-0000-000000000002";
        private const string CatOrnate  = "a1b2c3d4-0001-0000-0000-000000000003";
        private const string CatMinimal = "a1b2c3d4-0001-0000-0000-000000000004";
        private const string CatRustic  = "a1b2c3d4-0001-0000-0000-000000000005";
        private const string CatGallery = "a1b2c3d4-0001-0000-0000-000000000006";

        public override void Up()
        {
            // Add new columns
            Alter.Table("Products")
                .AddColumn("OverlayImage").AsString(int.MaxValue).Nullable()
                .AddColumn("AperturePercent").AsInt32().NotNullable().WithDefaultValue(15);

            // Seed aperture % for existing category-aligned products
            // Values match the sample PNG generator in SampleOverlayService
            Execute.Sql($@"UPDATE public.""Products"" SET ""AperturePercent"" = 18 WHERE ""CategoryId"" = '{CatClassic}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""AperturePercent"" = 10 WHERE ""CategoryId"" = '{CatModern}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""AperturePercent"" = 19 WHERE ""CategoryId"" = '{CatOrnate}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""AperturePercent"" = 5  WHERE ""CategoryId"" = '{CatMinimal}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""AperturePercent"" = 16 WHERE ""CategoryId"" = '{CatRustic}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""AperturePercent"" = 12 WHERE ""CategoryId"" = '{CatGallery}'");

            // Point seeded products to sample overlay PNGs generated by SampleOverlayService on startup
            Execute.Sql($@"UPDATE public.""Products"" SET ""OverlayImage"" = 'images/products/overlays/sample-classic.png' WHERE ""CategoryId"" = '{CatClassic}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""OverlayImage"" = 'images/products/overlays/sample-modern.png'  WHERE ""CategoryId"" = '{CatModern}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""OverlayImage"" = 'images/products/overlays/sample-ornate.png'  WHERE ""CategoryId"" = '{CatOrnate}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""OverlayImage"" = 'images/products/overlays/sample-minimal.png' WHERE ""CategoryId"" = '{CatMinimal}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""OverlayImage"" = 'images/products/overlays/sample-rustic.png'  WHERE ""CategoryId"" = '{CatRustic}'");
            Execute.Sql($@"UPDATE public.""Products"" SET ""OverlayImage"" = 'images/products/overlays/sample-gallery.png' WHERE ""CategoryId"" = '{CatGallery}'");
        }

        public override void Down()
        {
            Delete.Column("OverlayImage").FromTable("Products");
            Delete.Column("AperturePercent").FromTable("Products");
        }
    }
}
